version: '3.9'

services:
  agent:
    container_name: couchbase-agent
    build: .
    hostname: couchbase-agent 
    depends_on:
      - couchbase-server 
    environment:
      PORT: 8100
      CONNECTION_STRING: couchbase://db1
      CB_USERNAME: Administrator
      CB_PASSWORD: Passw0rd$12
    ports:
      - 8100:8100
    networks:
      - hasura 

  couchbase-server:
    build: ./couchbase-server
    ports:
      - 8091-8096:8091-8096
      - 11207:11207
      - 11210:11210
      - 11211:11211
      - 18091-18096:18091-18096
    environment:  
      - CLUSTER_NAME=db1
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=Passw0rd$$12
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    hostname: db1 
    container_name: couchbase-server
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true      
    networks:
      - hasura 
    entrypoint: [""]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"

  postgres:
    hostname: postgres 
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    networks:
      - hasura 

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
    - "8080:8080"
    hostname: hasura 
    depends_on:
    - postgres
    - agent
    restart: always
    networks:
      - hasura 
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

networks:
  hasura:
    driver: bridge

volumes:
  db_data:
