version: '3.9'

services:
  agent:
    container_name: couchbase-agent
    build: .
    depends_on:
      - db
    environment:
      - name=value
    ports:
      - 8100:8100
  db:
    image: couchbase:community
    deploy:
      replicas: 1
    ports:
      - 8091-8096:8091-8096
      - 11207:11207
      - 11210:11210
      - 11211:11211
      - 18091-18096:18091-18096

volumes:
  db_data:
