name: test-action
description: Test output of query of Hasura GraphQL against Couchbase Server
inputs:
  graphql-input:
    description: 'Graphql input tested against hasura endpoint'
    required: true
  n1q1-input:
    description: 'n1q1 input tested against couchbase server'
    required: true
outputs:
  result:
    description: 'Returns true if outputs are the same, else false'
runs: 
  using: "composite"
  steps:
    - run: "curl -H 'Content-Type: application/json' -d '{\"query\": \"${{ inputs.graphql-input }}\"}' http://localhost:8080/v1/graphql"
    - run: "curl -H 'Content-Type: application/json' -d '{\"statement\": \"${{ inputs.n1q1-input }}\"}' -u Administrator:Passw0rd$12 http://localhost:8093/query/service"
     